/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as CatequistaRouteImport } from './routes/catequista'
import { Route as IndexRouteImport } from './routes/index'

const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const CatequistaRoute = CatequistaRouteImport.update({
  id: '/catequista',
  path: '/catequista',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catequista': typeof CatequistaRoute
  '/matricula': typeof MatriculaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catequista': typeof CatequistaRoute
  '/matricula': typeof MatriculaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catequista': typeof CatequistaRoute
  '/matricula': typeof MatriculaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catequista' | '/matricula'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catequista' | '/matricula'
  id: '__root__' | '/' | '/catequista' | '/matricula'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatequistaRoute: typeof CatequistaRoute
  MatriculaRoute: typeof MatriculaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catequista': {
      id: '/catequista'
      path: '/catequista'
      fullPath: '/catequista'
      preLoaderRoute: typeof CatequistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatequistaRoute: CatequistaRoute,
  MatriculaRoute: MatriculaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
